### ISSUE TITLE
Make this Website responsive

### ISSUE THREAD

**Issue by rakshitmehra** [rakshitmehra/Quiz-application#1]

**Comment by seneenkhan** [comment]
Assign me this

**Comment by rakshitmehra** [comment]
Go Ahead

**Comment by void-ness** [comment]
Can I work in this?

**Comment by seneenkhan** [comment]
Sure

**Comment by rakshitmehra** [comment]
> Can I work in this? I intend to use media queries wherever required to make the website responsive. Other approach could be to use dynamic sizing

Yes you can do this. If you want to do than i can assign this to you

**Comment by void-ness** [comment]
Yes. I am interested. Kindly do

**Comment by rakshitmehra** [comment]
Go Ahead @void-ness
